version: '3.8'

services:
  web:
    build:
      context: ./assignment_7
      dockerfile: ../Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app_db
      - DB_USER=app_user
      - DB_PASSWORD=secret
      - logzIO_api_key=mFJpupXOLGfnACdjyGZlomwDdpxVfUFI
    depends_on:
      - db
    volumes:
      - ./assignment_7:/app # for live-reload during dev, optional

  reports-api:
    build:
      context: .
      dockerfile: ./reports/Dockerfile
    ports:
      - "5010:5010"
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app_db
      - DB_USER=app_user
      - DB_PASSWORD=secret
      - logzIO_api_key=mFJpupXOLGfnACdjyGZlomwDdpxVfUFI
    depends_on:
      - db
    volumes:
      - ./reports:/app/reports # for live-reload during dev, optional

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./assignment_7/pgdata:/var/lib/postgresql/data # bind-mount instead of named volume
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672" # RabbitMQ messaging port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass

  rabbit_api_gw:
    build:
      context: ./rabbit_api_gw
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AMQP_URL=amqp://user:pass@rabbitmq:5672
    depends_on:
      - rabbitmq

volumes:
  pgdata:
