version: '3.8'

services:
  web:
    build:
      context: ./assignment_7
      dockerfile: ../Dockerfile
    ports:
      - "5002:5001"
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app_db
      - DB_USER=app_user
      - DB_PASSWORD=secret
      - logzIO_api_key=mFJpupXOLGfnACdjyGZlomwDdpxVfUFI
    depends_on:
      - db
    volumes:
      - ./assignment_7:/app

  reports-api:
    build:
      context: .
      dockerfile: ./reports/Dockerfile
    ports:
      - "5010:5010"
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app_db
      - DB_USER=app_user
      - DB_PASSWORD=secret
      - logzIO_api_key=mFJpupXOLGfnACdjyGZlomwDdpxVfUFI
    depends_on:
      - db
    volumes:
      - ./reports:/app/reports

  page-view-counter:
    build:
      context: ./page-view-counter
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./page-view-counter:/app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=secret
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./assignment_7/pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
