version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app_db
      - DB_USER=app_user
      - DB_PASSWORD=secret
      - logzIO_api_key=mFJpupXOLGfnACdjyGZlomwDdpxVfUFI
    depends_on:
      - db
    volumes:
      - .:/app  # for live-reload during dev, optional

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # bind-mount instead of named volume
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
